"use strict";

const DOCUMENT_STATES = Object.freeze([
  "COLLECTING",
  "INCOMPLETE",
  "READY_FOR_REVIEW",
  "VERIFIED",
  "PREVIEW_READY",
  "COST_CALCULATED",
  "AWAITING_GENERATION_CONFIRMATION",
  "RECHARGE_REQUIRED",
  "GENERATION_IN_PROGRESS",
  "GENERATED",
  "DELIVERED",
  "RECOVERABLE_FAILURE",
  "CANCELLED",
]);

const DOCUMENT_EVENTS = Object.freeze({
  MARK_INCOMPLETE: "MARK_INCOMPLETE",
  CONTINUE_COLLECTING: "CONTINUE_COLLECTING",
  MARK_READY_FOR_REVIEW: "MARK_READY_FOR_REVIEW",
  VERIFY: "VERIFY",
  PREPARE_PREVIEW: "PREPARE_PREVIEW",
  CALCULATE_COST: "CALCULATE_COST",
  REQUEST_GENERATION_CONFIRMATION: "REQUEST_GENERATION_CONFIRMATION",
  REQUIRE_RECHARGE: "REQUIRE_RECHARGE",
  RECHARGE_CONFIRMED: "RECHARGE_CONFIRMED",
  START_GENERATION: "START_GENERATION",
  MARK_GENERATED: "MARK_GENERATED",
  MARK_DELIVERED: "MARK_DELIVERED",
  RECORD_RECOVERABLE_FAILURE: "RECORD_RECOVERABLE_FAILURE",
  RESUME: "RESUME",
  CANCEL: "CANCEL",
  MODIFY: "MODIFY",
});

const TRANSITIONS = Object.freeze({
  COLLECTING: Object.freeze({
    MARK_INCOMPLETE: "INCOMPLETE",
    MARK_READY_FOR_REVIEW: "READY_FOR_REVIEW",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  INCOMPLETE: Object.freeze({
    CONTINUE_COLLECTING: "COLLECTING",
    MARK_READY_FOR_REVIEW: "READY_FOR_REVIEW",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  READY_FOR_REVIEW: Object.freeze({
    VERIFY: "VERIFIED",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  VERIFIED: Object.freeze({
    PREPARE_PREVIEW: "PREVIEW_READY",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  PREVIEW_READY: Object.freeze({
    CALCULATE_COST: "COST_CALCULATED",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  COST_CALCULATED: Object.freeze({
    REQUEST_GENERATION_CONFIRMATION: "AWAITING_GENERATION_CONFIRMATION",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  AWAITING_GENERATION_CONFIRMATION: Object.freeze({
    REQUIRE_RECHARGE: "RECHARGE_REQUIRED",
    START_GENERATION: "GENERATION_IN_PROGRESS",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  RECHARGE_REQUIRED: Object.freeze({
    RECHARGE_CONFIRMED: "AWAITING_GENERATION_CONFIRMATION",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  GENERATION_IN_PROGRESS: Object.freeze({
    MARK_GENERATED: "GENERATED",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
    CANCEL: "CANCELLED",
  }),
  GENERATED: Object.freeze({
    MARK_DELIVERED: "DELIVERED",
    RECORD_RECOVERABLE_FAILURE: "RECOVERABLE_FAILURE",
  }),
  DELIVERED: Object.freeze({}),
  RECOVERABLE_FAILURE: Object.freeze({
    RESUME: null,
    CANCEL: "CANCELLED",
  }),
  CANCELLED: Object.freeze({}),
});

const EDITABLE_STATES = Object.freeze(new Set([
  "COLLECTING",
  "INCOMPLETE",
  "READY_FOR_REVIEW",
  "VERIFIED",
  "PREVIEW_READY",
  "COST_CALCULATED",
  "AWAITING_GENERATION_CONFIRMATION",
  "RECHARGE_REQUIRED",
]));

function resolveTransition(currentState, event, recoverableFailure = null) {
  if (!DOCUMENT_STATES.includes(currentState)) {
    return { ok: false, error: "DOCUMENT_STATE_INVALID" };
  }
  if (!Object.values(DOCUMENT_EVENTS).includes(event)) {
    return { ok: false, error: "DOCUMENT_EVENT_INVALID" };
  }
  if (event === DOCUMENT_EVENTS.MODIFY) {
    return EDITABLE_STATES.has(currentState)
      ? { ok: true, value: "COLLECTING" }
      : { ok: false, error: "DOCUMENT_MODIFICATION_FORBIDDEN" };
  }
  const nextState = TRANSITIONS[currentState]?.[event];
  if (event === DOCUMENT_EVENTS.RESUME && currentState === "RECOVERABLE_FAILURE") {
    const resumeState = recoverableFailure?.resume_state;
    if (!DOCUMENT_STATES.includes(resumeState) || resumeState === "RECOVERABLE_FAILURE") {
      return { ok: false, error: "DOCUMENT_RESUME_STATE_INVALID" };
    }
    return { ok: true, value: resumeState };
  }
  if (!nextState) return { ok: false, error: "DOCUMENT_TRANSITION_FORBIDDEN" };
  return { ok: true, value: nextState };
}

module.exports = {
  DOCUMENT_EVENTS,
  DOCUMENT_STATES,
  TRANSITIONS,
  resolveTransition,
};
