"use strict";

const MAX_INVOICE_ITEMS = 100;
const MAX_ITEM_DESCRIPTION_LENGTH = 300;
const MAX_ITEM_QUANTITY = 1_000_000;
const MAX_ITEM_UNIT_PRICE = 1_000_000_000;

module.exports = {
  MAX_INVOICE_ITEMS,
  MAX_ITEM_DESCRIPTION_LENGTH,
  MAX_ITEM_QUANTITY,
  MAX_ITEM_UNIT_PRICE,
};
